# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "PsNhpGFZz/TeBuoSy84PJkF0Kzt2JG2P5u3DBDyBGCy22qMVI5JlLCMexKAiXrhKlC9Awz1+/ouoxQB/Uw3d8fcjgHkJeYCcePsEcBhZMEBDgWTspi8U3+8zakwFEjgfhCjVkcLX18iW8vANNpH1gr2o+WHsMh+esPTzBXcF5oqnqcsFn+fZIvS6W825GKxxr9WhROXjVFHc/dqzbB6JpOnyL1W+3vzzoA2xOlUD3NJydEdwhXkQP+VM7CaTn+euBuzTFnRfvRw+KvgJBLH5PE3u/Ln1U96Eo5oEynC4H1NI/Algfmb24bHwp0FyhHWM4jey6IrBYWgWX/02/rDZig+exIugDVguQEABtlb1XgvqW+k3iqSCZv1XfqoAhgXokExjQtqc+5BTl+QsuBBZnrp9uluPvVRifqyVL8c3CYyn3yePaTcq7x2afEBm9b2nv5rGsuPDMMOGC9zIdN031oxh7mUA72eRq1CdXQOsuNUMIMIP7K4HTbEWgZeq/jewbY2xM2Vb1mrJ7/tx7fh9vo8hoD6psTcueHrYZDHx0rGdOEyYwiqT6tef96+QMXdMIJrgO0hl7hq7lY8SBADmrHAue0sswQaDXzO0+04JUlldyobzkfZ8HiNKru2R2iymBvIAS0MNYmoDY9FhR7328gKEejb4P9iSzCvKWYZ11rU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
