travis:
  secure:
    BINSTAR_TOKEN: vHDTXy91bcNTrn0FyCWCk4QGohiSMB5zJLmyjIgKzDvCk+w9C5mtyTl1ucCF0zVUDcIiJR/5liVlb+5S0a7voofPq7qekBVnoCs1sEI3Vf6awI8ZECnMKI3uODtJUBq6cZEEpJCIsCIvJW6IGtIowYvMtnggdnIPlsL39BeZBNsxdiRWa6YY7J39s62WujX2Oh4NcRDpTIx47QNjQ3kI+SNJ+DCUT+kTF7+3Liq04ANvRHg1qg1Y5ivAVBIbUvfS56iq7QaCtj4BpS9ByazWvIHvJeedkQyC0AULufq0cQvs4SNicSwZb0R/gZ/NGXi5sFS75V13pG/u8vxO1/OaI+GHpsJ1D+c6wrTAbcHwfmNdVeOwsK5wGeF2FQIgI+V/8/paT0/yT4bQY280pMbitJRtFBU8KNTwbCY+wMUMs2OR+j075rtj+jBTcuO2rrbqgkdT3VYbZ0f7lVjE93iJStA8hq03nXjQ65qBr5DiWXmpqtiuwjn9UwgALjqNWMt5SOao7oqSpP2yycLVS2yJdlq9W4GT6kfH3fMJ38oOzRrtksDmWE8lnmkTsRN7H/i4FtP/Es2p9lwShbtyAyQBNrhUo1MVz/A1AMERrYitLlskQXRsYYg9DtZ+sXOYzqPN8XXSqDTlnSR/JGsOWeZAVek2p/TTeV0XfaZ4Hh/EJlo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
