travis:
  secure:
    BINSTAR_TOKEN: l1a8aLuJIOeGpgRIyhh+5tsn19Mc2IqT6xhj2izoYLAbS78/ICjhkcwiC5/rOEhJL3cUufV7IbdZj5NTE7uCLwLVG3cpAz64nF25XwJn14cviH3heQUhSt+IZ4iWJGnmGyaOGV1OOz8h0gcVuEDlQGHnYhdi/YcDNUtpNizf1y5kve+MGlcmyVpOy1R5E6322cGSg+WQymkLhiM41ewRxSkxaFsaXY17q06TSgUyLwXbQaPRhhEbu+/eIWlhH0NLYGJ2R+BleNhcu+50Zja/lapFpUh/fs4hKXbR2nZj2AdWsAWy9KHHsSTcuG1GbZONcUD70PF40qgo5Jr7gXgjXWwa8u6IpsCnqb4x4TumAGQx8qDZywOhziVN9iFy2gKk+7QpIl+0jUhZsXHQxWj3k/O0ohIfFV0BVBuQPmJOTu8ceVakk+nSSbftyUDLs7JlLX0ETNIwM1FfiM9Coxh1HPCLFZTowigzBNTla1pkOk3Imx+yOXATa8jSnQofSEGZQJkLk4RNkDUj69QK09L0P9jwjgqeoygHx/9vQuGjM5KygFKrzovWaEccFVCr4nPdie5Bo0n33C8P4BO1SmO3rDy1TtBx59P9rL2Waw4mFW3Yjs0LcGZMmdFZPWSQt++55lNRSfgBvxoX5kTsVr/RGJxPqGS683SjHzS5+QdESgc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
