travis:
  secure:
    BINSTAR_TOKEN: g2VZ4jE/wjoWtG4a2XE+KVpog+y2MVvWDCOeTT+9CDZlFd1O6uPw9Wzz0xx+tG+YjQ4jGfTX1TGrFCzrdOO+IFkssfxX+YCILcVXM2nVllsnsmSwcfGSF2d9NOfR1CKAksnLIWvJ/xLOUCuLEnpnJCxPFinH5OsNGRt+c0wx9ellvk88yaeMvfDQTXGSeDK9nyPQdcOxNGbBSoBDFjfKHkvm8mjAo0ucB6+DNlyWxQ8Vdv416cjk8EV7f8g/IurEdxH2dg4dBj/TgADwxXoMH+miIsKMHEvAwvyW0+vbVjs3W3fMHcpl3mD5u0JG86bxRzY+sEJWWhErktFh/wzk/YKzhL2YMaVuMEw0Ntc1FELqtk0tAebmOQy4eYOMn7FwyJ9PsDeLkxwowUMXsVZ6o8ppGSAa4WIulo2V3V4Yjzp1HB4+sACfp0HYr2vNfiRFV0rTybMa3+KgQBg/iowyUDHEgnrsU39MIymRtdNUPvnDRANq6Og2ApqWaBCk/Xoxcvgk0ktVSRSGAdOPI8A3ZhRUekzk29N0AiGK4HBMHgnSZaAyZlwtaCYiN0+bMHj7G3AuZEZqCM/A2OBJpKFTES1xXiNPmw4k9eE0D8N1TVqRVmG3o/KeOprjlIY+pjPU385nJW42NrtT6XYkbHoy8qD6aTxCc+NxiC66LQDzq3I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
