travis:
  secure:
    BINSTAR_TOKEN: VsxXrRxHvlk8zEdkYmicU0LCw6vVxZmovSI+7l2b+KQy8my5Dlc5WyCgdzCqJEbvvGuOvx4AApx7RvnQa2spyAFcegYPHD4I7qG8Ox92g5xzarl9I59Z7dj7nV5JjC90r1Q0hMFuYTMYlrR5nq5jRO6JtSf2cUfl6NafsomZqCHMIsLvpGVxRWeDiYu6oE72wl1H4GkSN6eAohqzBadXOXjWmmKnksQDKgq5I5m0pPQjJIZWd5OYUSK/WWNEsOCmdCR1+gimjkKvQL4W46woZISEjqmp9x7KmdwYZVPXrUetRlApK+rKEw1YtZt2hYITXEzVgAhf53QFFtQMLU5yTThNi9hKTrmPDYZUjw9wBK9uXeBChqRkBu8X+Cf3NGFv4ky2JYYINInxg4jK9WcCGJk24UzUiQmSWImdoK6FoB03UcYOX0VtA/6JjXtawI6xFCjvaq6SWZQ+INyiFYvLUlFmgdCfucdChi74WNGRfuLXA3fp6q/yvzGNIxlpiYnaFyeRNwP4x++6e4EpCjK+Xx4FaTvjMFzkS7uqV2/G7sZfvGzrPdDgQ0JXcz7OC0+1Dev5xiuX+m3zy7wNUiiXJ/M01BrRgNMU9QVcB+KLVpkqWkXr8X2A+eNdWPPkg0fr/wGoE/qIiJ30GiA/s6sjT7dZ89NcY5WZr1MtSm31QuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
