travis:
  secure:
    BINSTAR_TOKEN: Uf1jBBHcbgcC16F5EkWlIVBdakvU+YCjjGGhSv2w4sp8bibEaqIKzR5k/h79P8UI+rl2w+DZm5ilGNLWWTJDZw8lrDS5IEkG7SSMQ0rkknvEpLmbiL7nhgHMvshLe+MMM/LxsGwbYLzYBP3h2DSfNg/5baVkENU59G+hOXRB1O9TIIVshQt0ssKJ1+eyu14hFjbgmndpveIRavh3pAocc6rQctzc2tPWOYBCOpiEUkJmu/Kf20xZY84W/RUAHrPSXKTv7P42J8ix95hmNAacM5Fab7vMbxURzEVk9XJlEClYURFlhCQ1i1GgVnr6z6VaCT3L9aWn4w4LaWSoNx/3QjdKmhs3nxSZTgEwuIY5Y2BUqJKfYMFvm3QwLEqyuao6dTYaH5kNSINNKzFvcHgjY6s+MLBF6ndgSQOH2LRTUEZVzev8wmKclv2XrowX/U/igtYmydO12SAFUD5Gx9CKwcUhaoZn/8zna0GSht4CzXEpCEdBr9YHE0octQtuwGbk9jGl0aGLt/EtmocaNO8w6m9SLMaiADIGsYzvb3ePmhLxYNjKp9GXWx3QyjN7ZV01nCJyUWqTIWHOtRgPwSpMD1EATPcbucEaCr10TOOdOhRthpSI0PkNT7fGnmKmjeDRS162+IL1Hw+7juxDlHLXawjS10WUg+bts/4hypb/QfA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
