travis:
  secure:
    BINSTAR_TOKEN: aZFVI2961m3MOoHnrDrbd+O1jf6T1UQp5HQZ/WDbsQakPSc9Fxu/aa/fGIqDftKFALUPPjP8b59OWFfULOpEUax9b61EDEZCHwCvcOecqpMXH9hnNTHTqrqUbWeND/i29edcD7zNPhmheUY5g+mGrz6dJbq6zRu7pfvdUGo+YpHLFnkO3EaQEd9GF1D9wy3UYBLk0oEBwQZa9Yn6FI8Y8Lwof20GeB/CjtKgYuFTlI8y/ZKnH4RP+yZELOI+d/fOycPcoqXIT/AkF4w8aH3H6QfTJEXBYbGn41pjUi7RsLqSoAH0+BLHJmTWnr8PzeHmxNR6wz3+GPOb+QkI7JgcRXVZu5N3IpBkm/e2d3V0fa2NkSzTgV+UkJfeKp4e0fRjUR05lnEEOZcpwpiNuKDcargcjSC0S4P1ClCqJ9f2u9UsbeXvwvuJYYkQ+4huGqvSU8QDsDERqPdnzQHrIcGd5ApEwUUoHuQ8myPKMa8teb+cUFeKarnhY1nUsMAKRppCHJkAHudy3glRX6p0w0RCBk2AggFnudlwlhCIyasIHxKXq0HVJEwStbA6Ua2rZhfZaENAEIiSHdwkUjeHL+ek5h+//62ZPDQTzoSk5PaBXZTqmfrgyXMKBIlHOBfbVgK92/txB4ZqPcSQERxwNI0U4SAMLoRqjRdjz3ZdCRvhNkg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
