travis:
  secure:
    BINSTAR_TOKEN: Rs/s9ErpGk9m0KIRCUtUc0BR+Zh9AWDuO1AG3Tjd0m07Iu+VqRmTkXbByMQZzJUhBePUMjDp3SK+RYFMQG6QyNSSgSrY8+/Jy3ATYG6bgq9HQnYoxpRWyOjiaYG+NtEgKzqx/nV4wIqVB4YICNgiu+sWRaMYGVmoOGu2YDuCc7/6bIspTl3uAJhHRxiGMturgd/jx8n8YQ+wlpYXjah64i0XaD5QP/legTN+4mYgf3o6R5at4+J5NDaxtEFoxU/s2mNVlKZHmhSRWp55/iDp6rc3h3cPPF8J8xlTnnLcpy/HmvTvxwMrUAs5QnV4dmkRalILoqImUzAGni+KY/jv2RbKyo+vmzArEmi8E2Ph2BVoMYh7u0LLr6msBstbcuHlP8rcYYwO85TDjBUuBhzYXakL1mgZcVRFYDAjTL3s9FasOI6BUu0aha8XxihYbHFBfIK/eXQgiyUY/oY13wePQ+xJgSvqB0LzRyBg2IQcu0P2Fn+0QMnoWztjgc+R4c8p0hfwf9IjwTgqGtayvNeKTdB6fhhiZh35rEDAuj84XwHOuw4yoS0J1u/uxuFFRPJtBRz1fCSYfkUNNK1Rtod51TfuWortjvO0U97j60ACMfaNFNq7M8sEFTXm0Z9DSEk9Vabs/PhdqUP4CdEP5ksxkFJT/6vAUqNAWj3onzPM8B8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
