travis:
  secure:
    BINSTAR_TOKEN: fSnBWhRMQB+8PPkSXAAiJDorBv7kFudQZSU4hq9IQprKm3KjgalLJ25ySRPCQ6OHLNBAihwG+EzXd/hAIUH9SOhqzUZk5VnwqbCTPh3MBeqGaKLItesv1z/btXh6qPtEaxHf7PV27Mo/cBonCYcxd9DOJwL6wRePFy6JX0vno0R+d1IXrviuXpIhzp8OdNjpi9KiR/iBWVxD13sm0/W52PXYvwZ0msQ4zV876nmJVb+m/dMNKkPNwG3oPGqoJR/dwCWNgY1sSn3Kc+fkLKuBkJWkzOf7f7LhaWghmJnrS+c7LJ+rsVAiTaCcjPCSm75TDWUu4GDIGhHBJSscViM4DK5+RDRPTOA2IN3vHrRMj63Yncqumy7kCteXNOJ0xWONUZ+zYOn+l3fDALUKgNDzviKMtYCCFxciTAd48xxCuIEWMVLHrXagTtU35a0GWGJLP584TM7sKtu9JrC3WEkIuTJ9H6LR588iXqls6SCQbdH4+1GkigxH2rWeld9phrfF38x4m0NSPZAFsrkxbh1n0hpcjEgvacWS1tiugKrbow1Krjv6pKc0CptM8c1Jpm4eP7Zx9UMSN3gK/WXAuZhtpUU7aT2NVyxtf3tbTH7fOTfUh16Gq7fdwuZu0TybeNfK0/BVFYGDy0J1i/LdFZFFxOGvYoSayctRjJgAOFPpipQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
