travis:
  secure:
    BINSTAR_TOKEN: S/HMWdq1Op1zSVTz6YvStkoH9VkZiw9jmgXX6EzVjP1nN4z20hO7QI/d7WlZMychlPcZZP+AsvhAL4QLwU/vgcJm14taOKrT9/9JGIhZFm7ewEskDrKlr6mK9Xkb2lXFy7KtzpQdKJHi3sXqzuXnsfJfVGDXYgYU4ljSwvHbbOcqpjtwCTZ7wpm7FHEpIFogAc6ykQCYU7Ug0Qf2Djpt+u8R9fezBF4BZWJw1n5eRXuBmxFYxWYXFf01eqiwau8srebG0h0+1M4bINj8bW2+eyJI/KocNAR5QblZBf5DJiO5E6tSSSpbwwXPChNr2ZI/9hN1t86BvfskxQ4xU+LihWTeSey8O6WgFiZB66hLn1dMUUmUCmvtJp+MqwFj8HqLejaXvrX+DAycEJ5CWf2l6G1TesBZDZxci+E+QmGGaVLD009OAXirx1KST7ak/QPmlAOaWSUa0mnZsvsPU7tNCMw6xLpj+bvb6CjJcK1q0Wbo0msjIrrTSEmPBCFDuBSwcqlfE0lOK73OTFJ1B7/7DJUFpcYmRlRt1btNUz5vrDXhxe8/u/q3ca0SHHjMhPgvhQJRsq0gYpEz9mG3lBLHrRYz8SDfKnhNMW8D3scyix+hFTIgfJN7P39tGWfoqyavLgdd8UdQJo3wXQjJmx3+jlm+DoEVV0DdF8yLuR8Zh1w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
