travis:
  secure:
    BINSTAR_TOKEN: ZRDLfT2gWmFA0BPlMmhxyYuqpDSN17TmhupJ9mPlT3xqXtfg0X/zhVhU1g8pP6HpRO3Io8jLlQXfH4G2fMmSJ0NpNepHhLdHNW/Y0j433jqmuAywKRBdJv9Zg6mCf81GpXVPZBdudOiijh+qVntgLCQxMB3WOPonoqdJBgEw+dznyhu7aLDlmXuUN/5VnAEzgGocv5c4ywhSooh5Si/oZN084QBF9vX+ohdN0RQVPhxh/N1mvD0RbxhGCLLa4b46NCTCFRJco9HT3j8p1KNJugDeU7oS2YXR7PTuZuA/9NBkv2qp2LLzMDZtxpUAz1tHHCP9IM1Mdn7iQlXUdeSqQWFR/fBtvxoAukVr0rjd4DtaWv8tAahVJtwTw0T60YV5mF+PZ9GbXUT+taDoJa9xSpakElBUq+1PPzA9jkj5CEUCwjXwPkiAc+2fcGpsz8LwEmq3701EhBVaYOslVWS2nnMrKGggTVKLJeUgu1oSNfpDteTe+vIfZUfTZuQPHpGQWjvZvRnDUNUf1nKTQwPbneJfIGTFWvG3vXeYR7ZRfxZJhurECMRtw2dyFl63MOqJ1a8KHYqxNTvUUecSIcazUpJsvLgcWtJAUJhQqIV9SM9/4rSy52qHJAsDy0HXLE8Eru25yz4FBs2zE/OBKmt9oGiInd1v+yU+AFLiS1sjdsE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
