travis:
  secure:
    BINSTAR_TOKEN: PsNhpGFZz/TeBuoSy84PJkF0Kzt2JG2P5u3DBDyBGCy22qMVI5JlLCMexKAiXrhKlC9Awz1+/ouoxQB/Uw3d8fcjgHkJeYCcePsEcBhZMEBDgWTspi8U3+8zakwFEjgfhCjVkcLX18iW8vANNpH1gr2o+WHsMh+esPTzBXcF5oqnqcsFn+fZIvS6W825GKxxr9WhROXjVFHc/dqzbB6JpOnyL1W+3vzzoA2xOlUD3NJydEdwhXkQP+VM7CaTn+euBuzTFnRfvRw+KvgJBLH5PE3u/Ln1U96Eo5oEynC4H1NI/Algfmb24bHwp0FyhHWM4jey6IrBYWgWX/02/rDZig+exIugDVguQEABtlb1XgvqW+k3iqSCZv1XfqoAhgXokExjQtqc+5BTl+QsuBBZnrp9uluPvVRifqyVL8c3CYyn3yePaTcq7x2afEBm9b2nv5rGsuPDMMOGC9zIdN031oxh7mUA72eRq1CdXQOsuNUMIMIP7K4HTbEWgZeq/jewbY2xM2Vb1mrJ7/tx7fh9vo8hoD6psTcueHrYZDHx0rGdOEyYwiqT6tef96+QMXdMIJrgO0hl7hq7lY8SBADmrHAue0sswQaDXzO0+04JUlldyobzkfZ8HiNKru2R2iymBvIAS0MNYmoDY9FhR7328gKEejb4P9iSzCvKWYZ11rU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
