travis:
  secure:
    BINSTAR_TOKEN: SXu0ztlvyuhQHxZKj8827v2U2pFICVzk8V59E8fpUqY/V5TP7e4DnM7n4q9Jk3Fl7/1M/sEmaU3HM9GVbrtenFrEcQXkpeD56KWosCUWwn+6mC7GM4bhnHX+jJFvbPIcub79bPavy+LsTXxd8sxSKkQ5wHgYKrYyMW5aW0DmGPTccBhk2jq53jsIP4+nHIq5CSiiMkwcXojykKENG9HrWD+5UpmSE+e5zAVf5GATcr/G3E2LIJyamB2EEMYQSYne4NQKGaGQum95t7tnrZCozRLwdpdwNyRZGz3iX/s3t8hbJzllvWx1GmxfH3aUbryW1mVAIStpqlj7UQ1peaUDoVreK12bk59YlfGRszBMc1Lo7mqzx27JWrEfjwOEUzJPWXadFCso25bm3ICmw1hfhGHSM+oXbNsejyqFq72rMwiTVjvB8W7nNyegcAHoWJ5KPjpDGt1R+lQB/YW9ZL72fIMnYzKhn+NUtAkUEWNS8fTB5/E9Q/3bbUZO6dBv2vVVHU7RVxowxnhW5Cn6Xp75rwTjsITYZKTlJ9ZTCHs20/bhWMLRQk66roIPdqdCJh/IXNOtR60vxG8If1fi7bh8+tnIuXp8VcU20RtbT8yzfpw0tURDg8MB03tsAvWmiObpiUhGEDuB9E8lDS2T9cxyia4XuRLSlO7ETFmcepcTecA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
