travis:
  secure:
    BINSTAR_TOKEN: EV4Jh9ZUwPGtTFmJDDrABjcf0ak0Pp8+lZ5HkOeQtDrefjtre04d4W3yTuPIyEmDI3MylMgIXLsFtc6H7Ruh6QBpw7jNFvHfu8tfG6UdDQysdbzWRxnErCeB+Cp3iUo+/bdzfxboe3DRQnr2ZPrTpZVKm+gUCW+nqHI/gzTqcuS44WmQVRdj/ZDdSwHOvjK0Nk00BpQXS05+YoJuBRaeeFpc5lku9aSmx24xJadoim0832fJveM6IzWJQBENywebnu6gYvymhl2fyoethhgIYf3KvqZ6jmJzQ306NhrZMwQ3PQwhlTet0eJhxpuAs2gZYF++aggmqoVJqc/OsPwPw2Jpfyq8oysQdjoO//dyWH/vKJjamGmFCOsjDrSXXmc1zCunUZD8ABSjlNoamPOFhyF1P6V0qAoCjBPBLmfBZ77DAJYLkPSkDetnH9j2AXWVhVRPACB9lhRQP6zcGDr7cCJwAdWIBHDUPUTl/BfIKRPeiajf12+TDnvk5PRU5sBUpSd+xFNpBFKAR8m0jHQQwxf5zxOnlIDP3+g+pw+M4VmAkDzVJ1HwFeFmmpP09hI5sibiHRJj4/KqevAD5lGRnE6B4Bc+F6Me1TKZEWKOgSmGRPHPvDuVkrzM4JQhMsZuNvt4oR6T0/M4XfhIm40E8QONyqT+GZM1IL/EaaLPxJs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
